#!/bin/sh

query=$(printf '%s' "$*" | tr ' ' '+' )
movie=$(curl -s https://1337x.wtf/search/$query/1/ | grep -m 1 -Eo "torrent\/[0-9]{7}\/[a-zA-Z0-9?%-]*/")
magnet=$(curl -s https://1337x.wtf/$movie | grep -m 1 -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*")
peerflix -k $magnet
